# -*- coding: utf-8 -*-
"""helperForProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lTeC8NCqZ84xRJjKnYzzjCieszFiUwYG

Canny Edge Detection
"""

t1=70
t2=3*t1
image = cv2.imread('/content/cube_6.jpg')
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
edges = cv2.Canny(gray, t1, t2)
plt.imshow(edges, cmap='gray')

"""Code for straight lines"""

import cv2
import numpy as np
from matplotlib import pyplot as plt
import matplotlib.lines as mlines

# Read the image
image = cv2.imread('/content/cube_three.jpg')
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

#resized_image = cv2.resize(gray, (300, 300))

# Detect edges using Canny Edge Detector
edges = cv2.Canny(gray, t1, t2)

# Define the minimum and maximum angle (in radians) for the lines
min_angle = (-20) * np.pi / 180  # Convert to radians
max_angle = (20) * np.pi / 180  # Convert to radians

# Detect lines using Hough Line Transform
lines = cv2.HoughLines(edges, 1.5, np.pi / 180,90, min_theta=min_angle, max_theta=max_angle)

# Draw the detected lines on the original image
if lines is not None:
    for rho, theta in lines[:, 0]:
        a = np.cos(theta)
        b = np.sin(theta)
        x0 = a * rho
        y0 = b * rho
        x1 = int(x0 + 2000 * (-b))
        y1 = int(y0 + 2000 * (a))
        x2 = int(x0 - 2000 * (-b))
        y2 = int(y0 - 2000 * (a))
        cv2.line(image, (x1, y1), (x2, y2), (0, 0, 255), 2)

# Save the image with detected lines
output_image_path = 'output_image.jpg'
cv2.imwrite(output_image_path, image)
print(f"Image with detected lines saved to {output_image_path}")

"""Code for small angles"""

import cv2
import numpy as np
from matplotlib import pyplot as plt
import matplotlib.lines as mlines

# Read the image
image = cv2.imread('/content/cube_three.jpg')
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Detect edges using Canny Edge Detector
edges = cv2.Canny(gray, t1, t2)

# Define the minimum and maximum angle (in radians) for the lines
min_angle = (40) * np.pi / 180  # Convert to radians
max_angle = (75) * np.pi / 180  # Convert to radians

# Detect lines using Hough Line Transform
lines = cv2.HoughLines(edges, 1.5, np.pi / 180, 90, min_theta=min_angle, max_theta=max_angle)

# Draw the detected lines on the original image
if lines is not None:
    for rho, theta in lines[:, 0]:
        a = np.cos(theta)
        b = np.sin(theta)
        x0 = a * rho
        y0 = b * rho
        x1 = int(x0 + 1000 * (-b))
        y1 = int(y0 + 1000 * (a))
        x2 = int(x0 - 1000 * (-b))
        y2 = int(y0 - 1000 * (a))
        cv2.line(image, (x1, y1), (x2, y2), (0, 0, 255), 2)

# Save the image with detected lines
output_image_path = 'output_image.jpg'
cv2.imwrite(output_image_path, image)
print(f"Image with detected lines saved to {output_image_path}")

"""Code for large angles"""

import cv2
import numpy as np
from matplotlib import pyplot as plt
import matplotlib.lines as mlines

# Read the image
image = cv2.imread('/content/cube_three.jpg')
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Detect edges using Canny Edge Detector
edges = cv2.Canny(gray, t1, t2)

# Define the minimum and maximum angle (in radians) for the lines
min_angle = (100) * np.pi / 180  # Convert to radians
max_angle = (140) * np.pi / 180  # Convert to radians

# Detect lines using Hough Line Transform
lines = cv2.HoughLines(edges, 1.5, np.pi / 180, 90, min_theta=min_angle, max_theta=max_angle)

# Draw the detected lines on the original image
if lines is not None:
    for rho, theta in lines[:, 0]:
        a = np.cos(theta)
        b = np.sin(theta)
        x0 = a * rho
        y0 = b * rho
        x1 = int(x0 + 2000 * (-b))
        y1 = int(y0 + 2000 * (a))
        x2 = int(x0 - 2000 * (-b))
        y2 = int(y0 - 2000 * (a))
        cv2.line(image, (x1, y1), (x2, y2), (0, 0, 255), 2)

# Save the image with detected lines
output_image_path = 'output_image.jpg'
cv2.imwrite(output_image_path, image)
print(f"Image with detected lines saved to {output_image_path}")